### ISSUE TITLE
[Idea] Pull settings from code repositories

### ISSUE THREAD

**Issue by shon** [shon/converge#2]
Developer starts a converge enabled app pointing to a git repo where the configs are stored. Converge will pull the settings file from that repo and loads the app configuration.

cc: @rohitkrai03

**Comment by rohitkrai03** [comment]
@shon A repo for just settings for a specific app doesn't make sense.  Settings don't mean anything unless in an app context. So, its better to have app settings inside the main app repo only.

**Comment by shon** [comment]
@rohitkrai03 many bigger projects have different repos for configs and app code. App code can be open source and config (obviously) private and sometimes managed by devops. So in this case it may pull config from config repo and provide converged config to app.
